"""add status pagination index

Revision ID: 07ffe6df5d84
Revises: 0e9b4da77ac3
Create Date: 2026-09-06 12:26:38.431836

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07ffe6df5d84"
down_revision: str | Sequence[str] | None = "0e9b4da77ac3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_events_status_received_at_event_id",
        "events",
        ["status", "received_at", "event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_status_received_at_event_id", table_name="events")
    # ### end Alembic commands ###
