"""add event pagination index

Revision ID: 0e9b4da77ac3
Revises: 7f403321615c
Create Date: 2026-09-03 17:07:50.593306

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e9b4da77ac3"
down_revision: str | Sequence[str] | None = "7f403321615c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_events_received_at_event_id",
        "events",
        ["received_at", "event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_received_at_event_id", table_name="events")
    # ### end Alembic commands ###
